version: '3.7'
services:
  process:
    build: ./process
    restart: on-failure
    volumes:
      - ./process:/usr/src/app
    depends_on:
      - database
  database:
    image: postgres:latest
    restart: on-failure
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    # Map a port to the host machine so a database GUI can be connected
    ports:
      - 4000:5432
volumes:
  postgres-data:
